global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'blackbox_exporter'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets: ['http://example.com']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'nginx_exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'process_exporter'
    static_configs:
      - targets: ['process-exporter:9256']

  - job_name: 'postgresql_exporter'
    static_configs:
      - targets: ['postgresql-exporter:9187']
