# inventories/hosts.yml

all:
  hosts:
    # Список хостов для Task 1.1
    # Используйте реальные IP-адреса ваших запущенных контейнеров
    dev-test-server-1:
      ansible_host: 172.20.0.10
    staging-test-server-1:
      ansible_host: 172.20.1.10 
    prod-test-server-1:
      ansible_host: 172.20.2.10
  vars:
    # Переменные, которые будут применены ко ВСЕМ хостам в этом инвентаре
    ansible_user: ansible_user # Пользователь
    ansible_password: wanderer33 # ВРЕМЕННО
    # Лучше использовать SSH-ключи или Ansible Vault!

# Опционально: Группы (на данный момент можно обойтись без них)
# dev_test_group:
#   hosts:
#     dev-test-server-1:

# staging_test_group:
#   hosts:
#     staging-test-server-1:

# prod_test_group:
#   hosts:
#     prod-test-server-1:
