# inventories/hosts.yml

all:
  vars:
    ansible_user: ansible_user
    ansible_password: wanderer33
    ansibl_host_key_checking: False

dev:
  hosts:
    dev-server-0:
      ansible_host: 172.20.0.10
    dev-server-1:
      ansible_host: 172.20.0.11
    dev-server-2:
      ansible_host: 172.20.0.12
    dev-server-3:
      ansible_host: 172.20.0.13
    dev-server-4:
      ansible_host: 172.20.0.14
    dev-server-5:
      ansible_host: 172.20.0.15
    dev-server-6:
      ansible_host: 172.20.0.16
    dev-server-7:
      ansible_host: 172.20.0.17

staging:
  hosts:
    staging-server-0:
      ansible_host: 172.20.1.10
    staging-server-1:
      ansible_host: 172.20.1.11
    staging-server-2:
      ansible_host: 172.20.1.12
    staging-server-3:
      ansible_host: 172.20.1.13
    staging-server-4:
      ansible_host: 172.20.1.14
    staging-server-5:
      ansible_host: 172.20.1.15
    staging-server-6:
      ansible_host: 172.20.1.16
    staging-server-7:
      ansible_host: 172.20.1.17

prod:
  hosts:
    prod-server-0:
      ansible_host: 172.20.2.10
    prod-server-1:
      ansible_host: 172.20.2.11
    prod-server-2:
      ansible_host: 172.20.2.12
    prod-server-3:
      ansible_host: 172.20.2.13
    prod-server-4:
      ansible_host: 172.20.2.14
    prod-server-5:
      ansible_host: 172.20.2.15
    prod-server-6:
      ansible_host: 172.20.2.16
    prod-server-7:
      ansible_host: 172.20.2.17
